### ISSUE TITLE
[Backend] endpoint zwracający listę lekarzy

### ISSUE THREAD

**Issue by OMIsie11** [pantalejmon/apsi#8]
Potrzebny jest endpoint dla zalogowanych, który zwraca listę lekarzy.
Aktualnie potrzebne informacje (do dodawania nowych wizyt) to:
- imię, nazwisko
- email lekarza
Więc endpoint potencjalnie mógłby zwracać listę lekarzy tylko z tymi informacjami.
Ewentualnie niech zwraca na razie wszystko dla zalogowanych, a ograniczy się to potem, kiedy będziemy wiedzieć, że nic więcej nie trzeba w innym miejscu.

**Comment by pantalejmon** [comment]
Endpoint dostępny pod `/api/doctor/list`
Wrzucam do pullrequesta
